// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-DS840PC22TZebeh9QIoKdQPsw9cAEs',
    appId: '1:175714378486:web:24fcc2f721fd8deef702d7',
    messagingSenderId: '175714378486',
    projectId: 'pushnotification-35029',
    authDomain: 'pushnotification-35029.firebaseapp.com',
    storageBucket: 'pushnotification-35029.appspot.com',
    measurementId: 'G-1V458RDWR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoup40JKEelld4rcLEpAtz6poxF1ez2HE',
    appId: '1:175714378486:android:7e803c4d1b947319f702d7',
    messagingSenderId: '175714378486',
    projectId: 'pushnotification-35029',
    storageBucket: 'pushnotification-35029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0XTet59_vcvwAQu0OyX5k7MoIkDWqXU',
    appId: '1:175714378486:ios:ec165eabe03bfc21f702d7',
    messagingSenderId: '175714378486',
    projectId: 'pushnotification-35029',
    storageBucket: 'pushnotification-35029.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe0XTet59_vcvwAQu0OyX5k7MoIkDWqXU',
    appId: '1:175714378486:ios:ec165eabe03bfc21f702d7',
    messagingSenderId: '175714378486',
    projectId: 'pushnotification-35029',
    storageBucket: 'pushnotification-35029.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-DS840PC22TZebeh9QIoKdQPsw9cAEs',
    appId: '1:175714378486:web:d3310f7aeeb40c88f702d7',
    messagingSenderId: '175714378486',
    projectId: 'pushnotification-35029',
    authDomain: 'pushnotification-35029.firebaseapp.com',
    storageBucket: 'pushnotification-35029.appspot.com',
    measurementId: 'G-4XJ1365RB0',
  );
}
